import { NivelJerarquicoConfig } from '../../../shared/components/catalogo-jerarquico/nivel-jerarquico.model';

export const NIVELES_GEOGRAFICO: NivelJerarquicoConfig[] = [
  {
    entidad: 'Pais',
    tituloSingular: 'País',
    tituloPlural: 'Países',
    siguienteRutaBase: '/catalogos/geografico/paises',
    siguienteSegmento: 'estados',
    siguienteEtiquetaBoton: 'Ver estados',
  },
  {
    entidad: 'Estado',
    tituloSingular: 'Estado',
    tituloPlural: 'Estados',
    campoPadre: 'paisId',
    entidadPadre: 'Pais',
    siguienteRutaBase: '/catalogos/geografico/estados',
    siguienteSegmento: 'municipios',
    siguienteEtiquetaBoton: 'Ver municipios',
  },
  {
    entidad: 'Municipio',
    tituloSingular: 'Municipio',
    tituloPlural: 'Municipios',
    campoPadre: 'estadoId',
    entidadPadre: 'Estado',
    siguienteRutaBase: '/catalogos/geografico/municipios',
    siguienteSegmento: 'localidades',
    siguienteEtiquetaBoton: 'Ver localidades',
  },
  {
    entidad: 'Localidad',
    tituloSingular: 'Localidad',
    tituloPlural: 'Localidades',
    campoPadre: 'municipioId',
    entidadPadre: 'Municipio',
    siguienteRutaBase: '/catalogos/geografico/localidades',
    siguienteSegmento: 'colonias',
    siguienteEtiquetaBoton: 'Ver colonias',
  },
  {
    entidad: 'Colonia',
    tituloSingular: 'Colonia',
    tituloPlural: 'Colonias',
    campoPadre: 'localidadId',
    entidadPadre: 'Localidad',
    siguienteRutaBase: '/catalogos/geografico/colonias',
    siguienteSegmento: 'calles',
    siguienteEtiquetaBoton: 'Ver calles',
  },
  {
    entidad: 'Calle',
    tituloSingular: 'Calle',
    tituloPlural: 'Calles',
    campoPadre: 'coloniaId',
    entidadPadre: 'Colonia',
  },
];
